# Generated by Django 6.0.1 on 2026-06-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_alter_product_usage_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('order_type', models.CharField(choices=[('single_yazd', 'تکی (یزد)'), ('bulk_iran', 'کلی (ایران)')], default='single_yazd', max_length=20, verbose_name='نوع سفارش')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='شهر')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('done', 'نهایی شد'), ('canceled', 'لغو شد')], default='new', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
