# Generated by Django 6.0.1 on 2026-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order_type',
            field=models.CharField(max_length=20, verbose_name='نوع سفارش'),
        ),
    ]
