# Generated by Django 6.0.1 on 2026-06-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderrequest_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='order_type',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='container_type',
            field=models.CharField(choices=[('1L', 'بطری ۱ لیتری'), ('2L', 'بطری ۲ لیتری'), ('4L', 'بطری ۴ لیتری'), ('10L', 'گالن ۱۰ لیتری'), ('20L', 'گالن ۲۰ لیتری')], default='1L', max_length=10, verbose_name='نوع ظرف'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='total_liters',
            field=models.FloatField(default=0, verbose_name='جمع کل به لیتر'),
        ),
    ]
