# Generated by Django 6.0.1 on 2026-06-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderrequest_order_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrequest',
            options={'verbose_name': 'درخواست سفارش', 'verbose_name_plural': 'درخواست\u200cهای سفارش'},
        ),
    ]
