# Generated by Django 6.0.1 on 2026-06-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrequest',
            options={},
        ),
    ]
