# Generated by Django 6.0.1 on 2026-06-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderrequest_options'),
        ('products', '0014_alter_productcontainerprice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='container_type',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='container_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcontainerprice', verbose_name='نوع ظرف'),
        ),
    ]
