# Generated by Django 5.2.7 on 2026-06-08 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderrequest_container_type_and_more'),
        ('products', '0015_alter_benefit_icon_alter_benefit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='container_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productcontainerprice', verbose_name='نوع ظرف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip کاربر'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='اطلاعات مرورگر کاربر'),
        ),
    ]
