# Generated by Django 5.2.7 on 2026-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderrequest_container_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
