# Generated by Django 5.2.7 on 2026-06-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_phoneverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
