# Generated by Django 5.2.7 on 2026-06-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_phoneverification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='cart_data',
            field=models.JSONField(blank=True, default=list, verbose_name='اقلام سفارش'),
        ),
    ]
