# Generated by Django 5.2.7 on 2026-06-20 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderrequest_cart_data'),
        ('products', '0017_alter_benefit_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='container_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcontainerprice', verbose_name='نوع ظرف'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
