# Generated by Django 5.2.7 on 2026-07-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderrequest_container_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrequest',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'لیست سفارش\u200cها'},
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
