# Generated by Django 6.0.1 on 2026-04-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_benefit_product_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='usage_instruction',
            field=models.TextField(blank=True, help_text='نحوه مصرف محصول'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='usage_time',
            field=models.CharField(blank=True, help_text='بهترین زمان مصرف (مثلاً صبح ناشتا)', max_length=200),
        ),
    ]
