# Generated by Django 6.0.1 on 2026-04-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_benefit_usage_instruction_benefit_usage_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='usage_instruction',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='usage_time',
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instruction',
            field=models.TextField(blank=True, help_text='نحوه مصرف محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_time',
            field=models.CharField(blank=True, help_text='بهترین زمان مصرف (مثلاً صبح ناشتا)', max_length=200),
        ),
    ]
