# Generated by Django 6.0.1 on 2026-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_benefit_usage_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage_condition',
            field=models.TextField(blank=True, help_text='شرایط نگهداری'),
        ),
    ]
