# Generated by Django 6.0.1 on 2026-04-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_storage_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='description',
        ),
    ]
