# Generated by Django 6.0.1 on 2026-04-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_benefit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='usage_time',
            field=models.TextField(blank=True, help_text='بهترین زمان مصرف (مثلاً صبح ناشتا)'),
        ),
    ]
