# Generated by Django 6.0.1 on 2026-06-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_usage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_10l',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت ۱۰ لیتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_1l',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت ۱ لیتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_20l',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت ۲۰ لیتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_2l',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت ۲ لیتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_4l',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت ۴ لیتری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
