# Generated by Django 6.0.1 on 2026-06-03 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_price_10l_product_price_1l_product_price_20l_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'مزیت', 'verbose_name_plural': 'مزایای محصولات'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_10l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_1l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_20l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_2l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_4l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_liter',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان مزیت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود است'),
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.benefit', verbose_name='مزایا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='هراچیک', max_length=100, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_condition',
            field=models.TextField(blank=True, verbose_name='شرایط نگهداری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_instruction',
            field=models.TextField(blank=True, verbose_name='نحوه مصرف محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_time',
            field=models.TextField(blank=True, verbose_name='بهترین زمان مصرف'),
        ),
        migrations.CreateModel(
            name='ProductContainerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(choices=[('1L', 'بطری ۱ لیتری'), ('2L', 'بطری ۲ لیتری'), ('4L', 'بطری ۴ لیتری'), ('10L', 'گالن ۱۰ لیتری'), ('20L', 'گالن ۲۰ لیتری')], max_length=10, verbose_name='نوع ظرف')),
                ('liters', models.PositiveIntegerField(help_text='مثلا ۱ یا ۲۰', verbose_name='حجم ظرف (لیتر)')),
                ('price_per_liter', models.PositiveIntegerField(verbose_name='قیمت هر لیتر (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_prices', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قیمت\u200cگذاری حجم',
                'verbose_name_plural': 'قیمت\u200cگذاری حجم\u200cها',
                'ordering': ['liters'],
                'unique_together': {('product', 'container_type')},
            },
        ),
    ]
