# Generated by Django 6.0.1 on 2026-06-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_benefit_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'مزیت', 'verbose_name_plural': 'مزیت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcontainerprice',
            options={'ordering': ('product', 'liters'), 'verbose_name': 'قیمت ظرف محصول', 'verbose_name_plural': 'قیمت\u200cهای ظرف محصولات'},
        ),
        migrations.AlterUniqueTogether(
            name='productcontainerprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usage_instruction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usage_time',
        ),
        migrations.AddField(
            model_name='productcontainerprice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='productcontainerprice',
            name='old_price_per_liter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت قبلی هر لیتر'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='آیکن'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='قابل سفارش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='productcontainerprice',
            name='container_type',
            field=models.CharField(choices=[('bottle', 'بطری'), ('gallon', 'گالن'), ('jar', 'جار'), ('other', 'سایر')], default='bottle', max_length=30, verbose_name='نوع ظرف'),
        ),
        migrations.AlterField(
            model_name='productcontainerprice',
            name='liters',
            field=models.PositiveIntegerField(verbose_name='حجم (لیتر)'),
        ),
        migrations.AddConstraint(
            model_name='productcontainerprice',
            constraint=models.UniqueConstraint(fields=('product', 'container_type', 'liters'), name='uniq_product_container_liters'),
        ),
    ]
