# Generated by Django 6.0.1 on 2026-06-03 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_benefit_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcontainerprice',
            name='uniq_product_container_liters',
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.benefit'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='storage_condition',
            field=models.TextField(blank=True, help_text='شرایط نگهداری'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instruction',
            field=models.TextField(blank=True, help_text='نحوه مصرف محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_time',
            field=models.TextField(blank=True, help_text='بهترین زمان مصرف (مثلاً صبح ناشتا)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_liter',
            field=models.DecimalField(decimal_places=1, default=1, help_text='حجم برحسب لیتر (مثلاً 1.0 یا 1.5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='هراچیک', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductContainerPrice',
        ),
    ]
