# Generated by Django 6.0.1 on 2026-06-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productcontainerprice_uniq_product_container_liters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_time',
            field=models.TextField(blank=True, help_text='بهترین زمان مصرف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_liter',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='حجم پایه (مثلاً 1.0)', max_digits=3),
        ),
        migrations.CreateModel(
            name='ProductContainerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(choices=[('plastic', 'بطری پلاستیکی'), ('glass', 'بطری شیشه\u200cای'), ('galon', 'گالن')], max_length=20, verbose_name='نوع ظرف')),
                ('volume_liter', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='حجم (لیتر)')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت واحد (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'قیمت بر اساس حجم',
                'verbose_name_plural': 'قیمت\u200cهای بر اساس حجم',
                'unique_together': {('product', 'container_type', 'volume_liter')},
            },
        ),
    ]
