# Generated by Django 6.0.1 on 2026-06-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_price_alter_product_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcontainerprice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productcontainerprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productcontainerprice',
            name='container_type',
            field=models.CharField(choices=[('1L', 'بطری ۱ لیتری'), ('2L', 'بطری ۲ لیتری'), ('4L', 'بطری ۴ لیتری'), ('10L', 'گالن ۱۰ لیتری'), ('20L', 'گالن ۲۰ لیتری')], max_length=10, verbose_name='نوع ظرف'),
        ),
        migrations.AlterField(
            model_name='productcontainerprice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcontainerprice',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='productcontainerprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_prices', to='products.product', verbose_name='محصول'),
        ),
        migrations.RemoveField(
            model_name='productcontainerprice',
            name='volume_liter',
        ),
    ]
