# Generated by Django 5.2.7 on 2026-06-08 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productcontainerprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ایکون کنار فواید'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان عرق'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجوده یا نه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='هراچیک', max_length=100, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/', verbose_name='آپلود عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشون بده در سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='چند لیترعرق در کارگاست'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_condition',
            field=models.TextField(blank=True, help_text='شرایط نگهداری', verbose_name='شرایط نگهداری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='زمان ویرایش محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_instruction',
            field=models.TextField(blank=True, help_text='نحوه مصرف محصول', verbose_name='نحوه مصرف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_time',
            field=models.TextField(blank=True, help_text='بهترین زمان مصرف', verbose_name='زمان مصرف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_liter',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='حجم پایه (مثلاً 1.0)', max_digits=3, verbose_name='حجم ظرف'),
        ),
        migrations.AlterField(
            model_name='productcontainerprice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
