# Generated by Django 5.2.7 on 2026-06-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_benefit_icon_alter_benefit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بیماری یا هدف درمانی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ (برای آدرس سایت)')),
            ],
            options={
                'verbose_name': 'هدف درمانی',
                'verbose_name_plural': 'اهداف درمانی',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='remedies',
            field=models.ManyToManyField(related_name='remedy_products', to='products.remedy', verbose_name='خواص درمانی (برای جستجو و فیلتر)'),
        ),
    ]
