# Generated by Django 5.2.7 on 2026-06-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remedy_product_remedies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': ' فواید', 'verbose_name_plural': 'فواید  عرقیجات '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی عرقیجات '},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' محصولات', 'verbose_name_plural': ' محصولات سایت '},
        ),
        migrations.AddField(
            model_name='remedy',
            name='icon_class',
            field=models.CharField(default='fa-leaf', help_text='مثلاً: fa-leaf یا fa-heart', max_length=50, verbose_name='کد آیکون (FontAwesome)'),
        ),
    ]
